### ISSUE TITLE
Edit PKGBUILD link

### ISSUE THREAD

**Issue by Devorlon** [flightlessmango/flightlessmango.com#11]
I'm terrible at web dev, and can't find the link but you should change the Mesa Hud PKGBUILD link under mango sources to the new location.

> https://github.com/flightlessmango/PKGBUILDS/blob/master/mangohud/PKGBUILD

**Comment by flightlessmango** [comment]
I totally forgot about that, thanks for the reminder! It's fixed now
[8c09c74](https://github.com/flightlessmango/flightlessmango.com/commit/8c09c7422260d5e95c11d693ee5c7ecc5ec037b0)
