### ISSUE TITLE
No Way to Upload Multiple Runs on One Benchmark 

### ISSUE THREAD

**Issue by gardotd426** [flightlessmango/flightlessmango.com#12]
Hey, I've seen your benchmarks where you have multiple runs all in one graph, but on the website it's not possible for users, at least it doesn't seem like it. After I upload a benchmark for one run, if I click "Edit Benchmark" and upload an additional one, it just replaces the original. There's no way to have more than one. Here are some screenshots, the benchmark has one file, and then I click "Edit Benchmark" and upload a second file, but then it just has the new benchmark and the original is gone.
![2020-02-25-014848_3286x1080_scrot](https://user-images.githubusercontent.com/54234607/75272873-b6cc2b00-57cc-11ea-9661-e6b38c813cfc.png)

![2020-02-25-014626_3286x1080_scrot](https://user-images.githubusercontent.com/54234607/75272853-ad42c300-57cc-11ea-9414-b89c04e2c438.png)
![2020-02-25-014635_3286x1080_scrot](https://user-images.githubusercontent.com/54234607/75272864-b2077700-57cc-11ea-8c19-e5dc828c4f8d.png)

**Comment by flightlessmango** [comment]
If you upload all of them at the same time it should work
