### ISSUE TITLE
Ruby exception when uploading benchmark

### ISSUE THREAD

**Issue by andrealmeid** [flightlessmango/flightlessmango.com#16]
Hello,

I just tried to upload two files of a captured benchmark and got the following exception:

```
NoMethodError in LogsController#create
undefined method `upload' for nil:NilClass 

    @game = @log.game
    respond_to do |format|
      if @log.save(:validate => false)     <---- this is the error line
        if @log.uploads.any?
          @log.parse_upload
        end

Application Trace:
app/controllers/logs_controller.rb:32:in `block in create'
app/controllers/logs_controller.rb:31:in `create' 
```

I tried with and without description, and used benchmarks files that worked fine in previous submissions, but the error still persists.

**Comment by andrealmeid** [comment]
It seems that the platform added broken logs to the system. Clicking on those links, and you can see the Ruby exceptions:

https://flightlessmango.com/games/9559/logs/135
https://flightlessmango.com/games/9559/logs/133
https://flightlessmango.com/games/9559/logs/132

**Comment by flightlessmango** [comment]
I accidentally broke the site yesterday, it's running in development right now which is not optimal and probably the cause of this issue. Hopefully I can fix it today, but so far I haven't had great luck in tracking down the underlying issue

**Comment by flightlessmango** [comment]
The issue should be resolved now, can you confirm? you probably need to reupload any broken ones

**Comment by andrealmeid** [comment]
It's working again, thanks :)
