### ISSUE TITLE
can't update benchmarks

### ISSUE THREAD

**Issue by ZerataX** [flightlessmango/flightlessmango.com#27]
whenever I try to update a benchmark I get redirected to a 422 error page stating

> **The change you wanted was rejected.**
> Maybe you tried to change something you didn't have access to.
> *If you are the application owner check the logs for more information.*

![error](https://user-images.githubusercontent.com/5024958/90304142-dce9a280-deb4-11ea-86dd-fb811fc74ac1.png)

**Comment by flightlessmango** [comment]
Should be fixed now, please verify

**Comment by ZerataX** [comment]
hmm I tried to rename a log and then to change colour but both resulted in this error again.
specifically this benchmark https://flightlessmango.com/games/6406/logs/735

**Comment by flightlessmango** [comment]
Hopefully fixed now, please try again

**Comment by ZerataX** [comment]
yes that did it. also thank you so much for this and mangohud!
